spring:
  profiles.default: dev
  jpa:
    hibernate.ddl-auto: validate
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
  output.ansi.enabled: always

logging.pattern.dateformat: yyyy-MM-dd HH:mm:ss

app.service.logger:
  enabled: false
  exceptions-type-only: true

---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

management.endpoints.web.exposure.include: health, prometheus

---
spring:
  config.activate.on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: postgres
