scrape_configs:
  - job_name: 'VenueApp'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'Venue Spring Boot App'
